server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://db4free.net:3306/botexample?logger=com.mysql.cj.log.StandardLogger&profileSQL=true&useTimezone=true&serverTimezone=GMT%2B3
    username: abiazverkhi
    password: assembler
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
